---
- hosts: all
  become: yes 
  gather_facts: yes 
  vars:
    user_name: Brice2024
    collor: red
  tasks:
     - name: Install passwd package 
       apt:
        name: passwd
        state: present 
       when: ansible_distribution not in "Debian, Ubuntu"
       tags:
        - app1
     - name: create group
       group:
        name: cloudteam
        state: present
 #     when: ansible_distribution_major_version < 9
     - name: create user
       user:
         name: "{{user_name}}"
         comment: Brice Admin
         group: cloudteam

- hosts: db 
  become: yes
  tasks: 
     - name: intall apache
       apt:
         name: apache2
         state: present 
     - name: start apache service
       service: name=apache2 state=started enabled=yes 
       tags:
        - service
     - name: Copy index file 
       copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644' 
     -    
